name: trivy

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '20 9 * * *'

concurrency: trivy

jobs:
  trivy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b

      - name: Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0105373003c89c494a3f436bd5efc57f3ac1ca20
        with:
          image-ref: "ghcr.io/yggdrion/shelly-cw:1"
          format: "table"
          exit-code: "1"
          ignore-unfixed: true
          vuln-type: "os,library"
          severity: "CRITICAL,HIGH"

  notification:
    needs: trivy
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      - name: Discord notification
        if: ${{ needs.trivy.result == 'failure' }}
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@08d9328877d6954120eef2b07abbc79249bb6210
        with:
          args: "{{ EVENT_PAYLOAD.repository.full_name }} - trivy error"
