name: trivy

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '20 9 * * *'

concurrency: trivy

jobs:
  trivy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8

      - name: Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@d63413b0a4a4482237085319f7f4a1ce99a8f2ac
        with:
          image-ref: "ghcr.io/yggdrion/shelly-cw:1"
          format: "table"
          exit-code: "1"
          ignore-unfixed: true
          vuln-type: "os,library"
          severity: "CRITICAL,HIGH"

  notification:
    needs: trivy
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      - name: Discord notification
        if: ${{ needs.trivy.result == 'failure' }}
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@0c4b27844ba47cb1c7bee539c8eead5284ce9fa9
        with:
          args: "{{ EVENT_PAYLOAD.repository.full_name }} - trivy error"
